version: '3.7'
services:
  web:
    build:
      context: .
      args:
        PROJ_NAME: "${PROJ_NAME}"
        PORT: "${PORT}"
    image: "${IMAGE}"
    privileged: true
    user: root
    ports:
      - "${PORT}:${PORT}"
    container_name: "${NODE_NAME}"
    environment:
      - COMPOSE_PROJECT_NAME="${PROJ_NAME}" 
    volumes:
      - .:/Code
